[package]
name = "gnome-simon"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_12"] }
libadwaita = "0.7.2"
gio = "0.20.9"
glib = "0.20.9"
